# Generated by Django 4.2.2 on 2023-07-05 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leaderboard_app.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laps', leaderboard_app.fields.FloatListField()),
                ('current_best', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-current_best'],
            },
        ),
    ]
