# Generated by Django 4.2.2 on 2023-07-05 13:30

from django.db import migrations, models
import leaderboard_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='current_best',
            field=models.FloatField(blank=True, default=-1.0),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='laps',
            field=leaderboard_app.fields.FloatListField(blank=True, default=[]),
        ),
    ]
