# Generated by Django 4.2.2 on 2023-07-05 13:33

from django.db import migrations
import leaderboard_app.fields


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard_app', '0002_alter_competitor_current_best_alter_competitor_laps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='laps',
            field=leaderboard_app.fields.FloatListField(blank=True, default=[], null=True),
        ),
    ]
